# TASK 1
dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("vgsalesGlobale - vgsalesGlobale.csv")
df.head(5)

Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [2]:
total_global_sales = df['Global_Sales'].sum()
print(f'Total Global Sales: {total_global_sales}')

Total Global Sales: 8920.44


In [3]:
# Find the game with the highest global sales
highest_sales_game = df.loc[df['Global_Sales'].idxmax()]
print(f'Game with Highest Global Sales: {highest_sales_game["Name"]} - {highest_sales_game["Global_Sales"]}')

Game with Highest Global Sales: Wii Sports - 82.74


In [4]:
# Determine the average sales for each region
average_sales = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print('Average Sales by Region:')
print(average_sales)

Average Sales by Region:
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [5]:
# Find the top 5 most popular game genres based on global sales
top_genres = df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print('Top 5 Game Genres by Global Sales:')
print(top_genres)


Top 5 Game Genres by Global Sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [6]:
# Calculate the total sales for each genre in each region
total_sales_by_genre = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
print('Total Sales by Genre in Each Region:')
print(total_sales_by_genre)

Total Sales by Genre in Each Region:
              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36


In [7]:

# Determine the most popular genre in North America (NA_Sales)
most_popular_genre_na = total_sales_by_genre['NA_Sales'].idxmax()
print(f'Most Popular Genre in North America: {most_popular_genre_na}')


Most Popular Genre in North America: Action


In [8]:
# Display last 10 rows
print('Last 10 Rows of the Dataset:')
print(df.tail(10))

Last 10 Rows of the Dataset:
        Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01

In [9]:
# Determine the top 3 gaming platforms with the highest global sales
top_platforms = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print('Top 3 Gaming Platforms by Global Sales:')
print(top_platforms)

Top 3 Gaming Platforms by Global Sales:
Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [10]:
# Calculate the market share for each genre
market_share = (total_sales_by_genre / total_sales_by_genre.sum()) * 100
print('Market Share by Genre:')
print(market_share)

Market Share by Genre:
               NA_Sales   EU_Sales   JP_Sales  Other_Sales
Genre                                                     
Action        19.982700  21.568281  12.389429    23.488562
Adventure      2.408404   2.634617   4.033245     2.107176
Fighting       5.089746   4.162473   6.765968     4.597932
Misc           9.338599   8.872985   8.346889     9.441554
Platform      10.176533   8.283452  10.129200     6.466938
Puzzle         2.817697   2.086166   4.439126     1.573175
Racing         8.181746   9.793643   4.391102     9.685992
Role-Playing   7.450119   7.725964  27.289275     7.472266
Shooter       13.262159  12.869896   2.965097    12.872454
Simulation     4.172822   4.657927   4.934083     3.951113
Sports        15.555606  15.481918  10.485508    16.918834
Strategy       1.563869   1.862678   3.831079     1.424005


In [11]:
correlation = df['NA_Sales'].corr(df['EU_Sales'])
print(f'Correlation Coefficient between NA_Sales and EU_Sales: {correlation}')
# ... existing code ...

Correlation Coefficient between NA_Sales and EU_Sales: 0.767726748370263


## Task 2 English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [1]:
# Create English-Spanish dictionary
english_spanish = {
    'hello': 'hola',
    'goodbye': 'adiós',
    'thank you': 'gracias',
    'please': 'por favor',
    'water': 'agua',
    'food': 'comida',
    'friend': 'amigo',
    'house': 'casa',
    'car': 'coche',
    'time': 'tiempo'
}

print("Welcome to the English-Spanish Dictionary!")
print("Enter 'quit' to exit")

while True:
    word = input("\nEnter an English word: ").lower()
    
    if word == 'quit':
        print("¡Adiós! Goodbye!")
        break
        
    if word in english_spanish:
        print(f"Spanish translation: {english_spanish[word]}")
    else:
        print("Translation not available in dictionary")

Welcome to the English-Spanish Dictionary!
Enter 'quit' to exit
Translation not available in dictionary
Translation not available in dictionary
Translation not available in dictionary
Translation not available in dictionary
Translation not available in dictionary
Translation not available in dictionary
Translation not available in dictionary
Translation not available in dictionary
Translation not available in dictionary
Translation not available in dictionary
Translation not available in dictionary
Spanish translation: por favor
¡Adiós! Goodbye!



## Task 3 Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [2]:
def classify_emails(emails):
    important_keywords = ["urgent", "important", "deadline", "meeting"]
    promotions_keywords = ["sale", "discount", "promotion", "deal"]
    spam_keywords = ["lottery", "prince", "rich", "money"]
    
    important_emails = []
    promotions_emails = []
    spam_emails = []
    
    for email in emails:
        email_lower = email.lower()
        
        if any(keyword in email_lower for keyword in important_keywords):
            important_emails.append(email)
        elif any(keyword in email_lower for keyword in promotions_keywords):
            promotions_emails.append(email)
        elif any(keyword in email_lower for keyword in spam_keywords):
            spam_emails.append(email)
        else:
            spam_emails.append(email)
    
    print("Important Emails:")
    print(important_emails)
    print("\nPromotions Emails:")
    print(promotions_emails)
    print("\nSpam Emails:")
    print(spam_emails)
    
    return important_emails, promotions_emails, spam_emails

# Example usage:
sample_emails = [
    "Urgent: Please review the attached meeting agenda",
    "Huge Sale! Get 50% discount on our new products",
    "Congratulations! You just won the lottery",
    "Reminder: Project deadline is next week",
    "Exclusive promotion deal just for you!",
    "Let's get rich quickly by investing in this scheme"
]

classify_emails(sample_emails)

Important Emails:
['Urgent: Please review the attached meeting agenda', 'Reminder: Project deadline is next week']

Promotions Emails:
['Huge Sale! Get 50% discount on our new products', 'Exclusive promotion deal just for you!']

Spam Emails:
['Congratulations! You just won the lottery', "Let's get rich quickly by investing in this scheme"]


(['Urgent: Please review the attached meeting agenda',
  'Reminder: Project deadline is next week'],
 ['Huge Sale! Get 50% discount on our new products',
  'Exclusive promotion deal just for you!'],
 ['Congratulations! You just won the lottery',
  "Let's get rich quickly by investing in this scheme"])

## Task 4 Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.

In [3]:
shopping_cart = []
products = ["AI Response Simulator", "Investment Decision", "Checkout"]

print("Welcome to the Online Store!")
print("Available products:")
for i, product in enumerate(products, start=1):
    print(f"{i}. {product}")

while True:
    choice = input("Enter the product number to add to cart (or 'q' to quit): ").lower()
    if choice == 'q':
        break
    try:
        choice_num = int(choice)
        if 1 <= choice_num <= 3:
            selected_product = products[choice_num - 1]
            if selected_product != "Checkout":
                shopping_cart.append(selected_product)
                print(f"Added '{selected_product}' to your cart.")
            else:
                break
        else:
            print("Invalid selection. Please choose a valid product number.")
    except ValueError:
        print("Please enter a valid number or 'q' to quit.")

print("Your shopping cart contains:")
for item in shopping_cart:
    print(f"- {item}")
print("Thank you for shopping with us. Goodbye!")

Welcome to the Online Store!
Available products:
1. AI Response Simulator
2. Investment Decision
3. Checkout
Added 'AI Response Simulator' to your cart.
Added 'Investment Decision' to your cart.
Your shopping cart contains:
- AI Response Simulator
- Investment Decision
Thank you for shopping with us. Goodbye!


## Task 5
* Create two NumPy arrays of the same shape and perform element-wise addition on them.
* Calculate the element-wise product of two NumPy arrays.

In [5]:
import numpy as np
# Create two NumPy arrays of the same shape
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Perform element-wise addition
addition_result = arr1 + arr2

# Perform element-wise product
product_result = arr1 * arr2

print("Element-wise addition:")
print(addition_result)

print("\nElement-wise product:")
print(product_result)

Element-wise addition:
[ 6  8 10 12]

Element-wise product:
[ 5 12 21 32]


## Task 6
* Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

* Concatenate two NumPy arrays horizontally and vertically.

In [6]:
# Reshape a 1D NumPy array into a 2D array (3x4)
arr_1d_task6 = np.arange(1, 13)
arr_2d_task6 = arr_1d_task6.reshape(3, 4)
print("Reshaped 2D array (3x4):")
print(arr_2d_task6)

# Concatenate two NumPy arrays horizontally
horizontal_concat = np.hstack((arr1, arr2))
print("\nHorizontal Concatenation:")
print(horizontal_concat)

# Concatenate two NumPy arrays vertically
vertical_concat = np.vstack((arr1, arr2))
print("\nVertical Concatenation:")
print(vertical_concat)

Reshaped 2D array (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Horizontal Concatenation:
[1 2 3 4 5 6 7 8]

Vertical Concatenation:
[[1 2 3 4]
 [5 6 7 8]]


## Task 7
* Reverse A List In Python Using Slicing


In [7]:
example_list = [10, 20, 30, 40, 50]
reversed_list = example_list[::-1]
print("Original list:", example_list)
print("Reversed list:", reversed_list)

Original list: [10, 20, 30, 40, 50]
Reversed list: [50, 40, 30, 20, 10]


# TASK 8
You need to download the GitHub Desktop software, push your lab task to your GitHub account, and share the link on GCR as a submission.